config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks/new', to: 'tasks#new'

  post '/tasks', to: 'tasks#create'

  get '/tasks', to: 'tasks#index', as: :all_tasks

  get '/tasks/:id', to: 'tasks#show', as: :task

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show, :edit]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end



  private

  def task_params
    params.require(:task).permit(:title, :details, :completed, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>hello, edit and update the task</h1>

<%= form_for(@task) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.label :completed %>
  <%= form.text_field :completed %>
  <%= form.submit %>

<% end %>

app/views/tasks/index.html.erb
<!-- <h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p> -->
<h1>All tasks</h1>
  <ol>
    <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
    <% end %>
  </ol>

app/views/tasks/new.html.erb
<h1>hello, create a new task</h1>
<%= form_for(@task) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.label :completed %>
  <%= form.text_field :completed %>
  <%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%=@task.completed%></p>
<%= link_to 'all tasks', all_tasks_path %>
<%= link_to 'create task', tasks_new_path %>
<%= link_to 'edit task', edit_task_path(@task) %>

 <%= link_to 'delete this task', task_path(@task), method: :delete, data: {confirm: 'are you really sure???'}  %>